name: {{ cookiecutter.package_name }}
version: {{ cookiecutter.version }}
synopsis: {{ cookiecutter.description }}
description: {{ cookiecutter.description }}
category: API
author: {{ cookiecutter.author }} <{{ cookiecutter.email }}>
maintainer: {{ cookiecutter.author }} <{{ cookiecutter.email }}>
copyright: {{ cookiecutter.year }} {{ cookiecutter.author }}
{% if cookiecutter.license_file == 'y' %}license: MIT{% else %}license: NONE{% endif %}
{% if cookiecutter.git_url %}git: {{ cookiecutter.git_url}}{% endif %}
dependencies:
- base >=4.13 && <5.0
- persistent
- persistent-template
- persistent-postgresql
- dotenv
- wai-extra
- wai-cors
- mtl
- hslogger
- fast-logger
- monad-logger
- http-types
- optparse-applicative
- utf8-string
- base64-bytestring
- hedis
- time
- safe
- wai
- warp
- bcrypt
- text
- bytestring
library:
  source-dirs: src
  ghc-options: -fwarn-unused-imports
  exposed-modules:
  - Api
  - Api.Service
  - Api.User
  - Cache
  - Cli
  - Config
  - Db
  - Elasticsearch
  - Logger
  - Models
  - Model.User
  - Utils
  dependencies:
  - aeson
  - bloodhound
  - http-client
  - monad-control
  - servant
  - servant-auth
  - servant-server
  - transformers
  - containers
  - unordered-containers
executables:
  {{ cookiecutter.package_name }}:
    main: app/Main.hs
    ghc-options: 
    - -fwarn-unused-imports
    - -fwrite-ide-info
    - -hiedir=./hie
    dependencies:
    - {{ cookiecutter.package_name }}
